import React, { useEffect, useMemo, useState } from 'react';
import { Users, Search, MessageSquare, Download, CheckCircle2 } from 'lucide-react';
import { useShop } from '../../context/ShopContext';
import { supabase } from '../../lib/supabase';
import { buildCustomerIndex, CustomerRecord } from '../../lib/customerIndex';
import { sanitizeRowForCsv } from '../../utils/csvSafe';

interface CustomersViewProps { dbUsers?: any[]; }

export const CustomersView: React.FC<CustomersViewProps> = ({ dbUsers: propDbUsers }) => {
  const { orders = [], formatPrice, showToast } = useShop();
  const [localUsers, setLocalUsers] = useState<any[]>(propDbUsers || []);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCustomer, setSelectedCustomer] = useState<CustomerRecord | null>(null);
  const [isLoading, setIsLoading] = useState(propDbUsers === undefined);

  useEffect(() => {
    if (propDbUsers !== undefined) { setLocalUsers(propDbUsers); setIsLoading(false); return; }
    let mounted = true;
    const load = async () => {
      setIsLoading(true);
      const { data, error } = await supabase.from('profiles').select('id,name,email,phone,default_governorate,default_city,default_address,role').limit(2000);
      if (error) { console.error(error); showToast('Failed to load customer profiles', 'warning'); }
      if (mounted) { setLocalUsers((data || []).map((p: any) => ({ uid: p.id, name: p.name || '', email: p.email || '', phone: p.phone || '', defaultGovernorate: p.default_governorate || '', defaultCity: p.default_city || '', defaultAddress: p.default_address || '', avatar: '', role: p.role }))); setIsLoading(false); }
    };
    load();
    return () => { mounted = false; };
  }, [propDbUsers]);

  const customersList = useMemo(() => Array.from(buildCustomerIndex(localUsers as any, orders).values()), [localUsers, orders]);
  const filteredCustomers = useMemo(() => { const q = searchQuery.trim().toLowerCase(); if (!q) return customersList; return customersList.filter(c => [c.name,c.email,c.phone,c.city,c.governorate].filter(Boolean).some(v => String(v).toLowerCase().includes(q))); }, [customersList, searchQuery]);

  const handleWhatsApp = (phone: string | null, name: string) => { if (!phone) return showToast('No phone number on file', 'warning'); const clean = phone.replace(/[^0-9]/g, ''); const msg = encodeURIComponent(`Marhaba ${name}! This is Yalla.lb Merchant Support regarding your orders. How can we assist you today?`); window.open(`https://wa.me/${clean}?text=${msg}`, '_blank', 'noopener,noreferrer'); showToast(`Opening WhatsApp chat for ${name}`, 'info'); };
  const handleExport = async () => { const Papa = await import('papaparse'); const rows = filteredCustomers.map(c => sanitizeRowForCsv({ customer_id:c.id,name:c.name,email:c.email||'',phone:c.phone||'',governorate:c.governorate||'',city:c.city||'',street_address:c.street||'',orders_count:c.ordersCount,total_spent_usd:c.totalSpentUSD.toFixed(2),last_order_date:c.lastOrderDate||'No orders yet' })); const csv = Papa.unparse(rows); const blob = new Blob([csv], {type:'text/csv;charset=utf-8;'}); const url = URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=`yalla_customers_report_${new Date().toISOString().slice(0,10)}.csv`; a.click(); URL.revokeObjectURL(url); showToast('Customers report downloaded successfully','success'); };

  return <div className="space-y-6">
    <div className="bg-white p-6 rounded-3xl border border-slate-200/80 shadow-xs flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-2.5"><div className="w-10 h-10 rounded-2xl bg-indigo-50 flex items-center justify-center text-[#4f46e5]"><Users className="w-5 h-5"/></div><div><h2 className="text-xl font-bold text-slate-900">Customers Directory</h2><p className="text-xs text-slate-500">Manage buyers, lifetime spend, WhatsApp communications, and order histories.</p></div></div><div className="flex items-center gap-3"><button onClick={handleExport} className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-bold border border-slate-200"><Download className="w-3.5 h-3.5"/>Download Report</button><span className="px-3.5 py-1.5 rounded-full text-xs font-black bg-indigo-50 text-indigo-700 border border-indigo-100">{customersList.length} Customer{customersList.length===1?'':'s'}</span></div></div>
    <div className="relative flex-1 min-w-[280px]"><Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2"/><input value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} placeholder="Search by customer name, phone number, email, or city..." className="w-full pl-10 pr-4 py-2.5 bg-white text-xs rounded-2xl border border-slate-200 focus:outline-none focus:border-indigo-600"/></div>
    <div className="bg-white rounded-3xl border border-slate-200/80 shadow-xs overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-xs text-slate-700"><thead className="bg-slate-50/80 text-[11px] uppercase font-bold text-slate-500 tracking-wider"><tr><th className="p-4">Customer</th><th className="p-4">Contact Info</th><th className="p-4">Location (Lebanon)</th><th className="p-4">Total Orders</th><th className="p-4">Lifetime Spend</th><th className="p-4">Last Activity</th><th className="p-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filteredCustomers.map(c=><tr key={c.id} className="hover:bg-slate-50/60"><td className="p-4"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-full bg-indigo-100 text-indigo-700 font-black flex items-center justify-center">{c.name.slice(0,2).toUpperCase()}</div><div><div className="font-bold text-slate-900">{c.name}</div><div className="text-[11px] text-slate-400">{c.email||'—'}</div></div></div></td><td className="p-4">{c.phone ? <><div className="font-mono font-semibold">{c.phone}</div><div className="text-[10px] text-emerald-600 font-semibold flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/> WhatsApp Enabled</div></> : <span className="text-slate-400">No contact on file</span>}</td><td className="p-4"><div className="font-medium">{c.city||'—'}</div><div className="text-[11px] text-slate-400">{c.governorate||'—'}</div></td><td className="p-4"><span className="px-2.5 py-0.5 rounded-full text-xs font-bold bg-slate-100">{c.ordersCount}</span></td><td className="p-4 font-black text-slate-900">{formatPrice(c.totalSpentUSD)}</td><td className="p-4 text-slate-500 text-[11px]">{c.lastOrderDate||'—'}</td><td className="p-4 text-right"><div className="flex justify-end gap-2"><button onClick={()=>handleWhatsApp(c.phone,c.name)} className="p-2 rounded-xl bg-emerald-50 text-emerald-700 hover:bg-emerald-600 hover:text-white"><MessageSquare className="w-4 h-4"/></button><button onClick={()=>setSelectedCustomer(c)} className="px-3 py-1.5 rounded-xl bg-slate-100 text-slate-700 text-xs font-bold">View Orders</button></div></td></tr>)}</tbody></table></div>{isLoading?<div className="p-12 text-center text-slate-500">Loading customers…</div>:filteredCustomers.length===0?<div className="p-16 text-center text-slate-500">No matching customers found.</div>:null}</div>
    {selectedCustomer && <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs"><div className="bg-white max-w-2xl w-full p-6 sm:p-8 rounded-3xl shadow-2xl space-y-6 max-h-[90vh] overflow-y-auto"><div className="flex justify-between pb-4 border-b"><div><h3 className="text-lg font-bold">{selectedCustomer.name}</h3><p className="text-xs text-slate-500">{selectedCustomer.phone} • {selectedCustomer.city}, {selectedCustomer.governorate}</p></div><button onClick={()=>setSelectedCustomer(null)} className="text-slate-400 text-lg">✕</button></div><div className="grid grid-cols-3 gap-3 text-xs"><div className="p-3 bg-slate-50 rounded-2xl"><span className="text-slate-400 block">TOTAL ORDERS</span><b className="text-lg">{selectedCustomer.ordersCount}</b></div><div className="p-3 bg-slate-50 rounded-2xl"><span className="text-slate-400 block">LIFETIME VALUE</span><b className="text-lg text-emerald-600">{formatPrice(selectedCustomer.totalSpentUSD)}</b></div><div className="p-3 bg-slate-50 rounded-2xl"><span className="text-slate-400 block">LOCATION</span><b>{selectedCustomer.city||'—'}</b></div></div><div className="space-y-3"><h4 className="text-xs font-bold uppercase tracking-wider text-slate-400">Order History</h4>{selectedCustomer.recentOrders.length ? selectedCustomer.recentOrders.map(o=><div key={o.id} className="p-4 rounded-2xl border bg-slate-50/50"><div className="flex justify-between text-xs font-bold"><span className="text-indigo-600 font-mono">#{o.id}</span><span>{formatPrice(o.totalUSD)}</span></div><div className="text-[11px] text-slate-500 mt-2">{o.items.map(i=>`${i.quantity}x ${i.product.name}`).join(', ')}</div><div className="flex justify-between text-[10px] text-slate-400 mt-2"><span>Date: {o.date}</span><span className="px-2 py-0.5 rounded-full bg-slate-200">{o.status}</span></div></div>) : <p className="text-xs text-slate-400 text-center py-4">No completed orders yet for this profile.</p>}</div><div className="flex justify-end"><button onClick={()=>handleWhatsApp(selectedCustomer.phone,selectedCustomer.name)} className="px-4 py-2 bg-emerald-600 text-white rounded-xl text-xs font-bold flex items-center gap-1.5"><MessageSquare className="w-3.5 h-3.5"/>Message on WhatsApp</button></div></div></div>}
  </div>;
};
export default CustomersView;
