import React, { useEffect, useMemo, useState } from 'react';
import { Activity, Search, Trash2, Copy, Check, RefreshCw, Database, AlertCircle, CheckCircle2, Clock, Layers, ChevronDown, ChevronUp, Cpu, ShieldCheck, Zap, Download, Terminal, FileCheck, AlertTriangle } from 'lucide-react';
import { useShop } from '../../context/ShopContext';
import { supabase } from '../../lib/supabase';

type AuditRow = { id:string; actor_id?:string|null; action_type?:string|null; summary?:string|null; details?:string|null; target_id?:string|null; snapshot_before?:any; snapshot_after?:any; created_at:string; ip_address?:string|null; user_agent?:string|null; table_name?:string|null; operation?:string|null };
export const DatabaseActivityLogs: React.FC = () => {
  const { products, orders, showToast } = useShop();
  const [rows,setRows]=useState<AuditRow[]>([]); const [loading,setLoading]=useState(true); const [query,setQuery]=useState(''); const [tab,setTab]=useState<'operations'|'pipeline'>('operations'); const [expanded,setExpanded]=useState<string|null>(null); const [copied,setCopied]=useState<string|null>(null); const [diagnostic,setDiagnostic]=useState<{ok:boolean;ms:number;message:string}|null>(null); const [running,setRunning]=useState(false);
  const load=async()=>{setLoading(true);const {data,error}=await supabase.from('admin_activities').select('*').order('created_at',{ascending:false}).limit(500);if(error)showToast(error.message,'warning');else setRows((data||[]) as AuditRow[]);setLoading(false)};
  useEffect(()=>{load();const ch=supabase.channel('admin-activities-live').on('postgres_changes',{event:'*',schema:'public',table:'admin_activities'},()=>load()).subscribe();return()=>{void supabase.removeChannel(ch)}},[]);
  const filtered=useMemo(()=>rows.filter(r=>{const q=query.toLowerCase();return !q||[r.action_type,r.summary,r.details,r.table_name,r.operation,r.target_id,r.actor_id,r.ip_address].filter(Boolean).some(v=>String(v).toLowerCase().includes(q))}),[rows,query]);
  const runDiagnostic=async()=>{setRunning(true);const start=performance.now();const {error}=await supabase.from('admin_activities').select('id').limit(1);const ms=Math.round(performance.now()-start);setDiagnostic({ok:!error,ms,message:error?`Supabase diagnostic failed: ${error.message}`:`Supabase authenticated read completed in ${ms}ms.`});showToast(error?error.message:`Supabase health check passed (${ms}ms)` ,error?'warning':'success');setRunning(false)};
  const copyLog=(r:AuditRow)=>{navigator.clipboard.writeText(JSON.stringify(r,null,2));setCopied(r.id);showToast('Copied audit JSON','info');setTimeout(()=>setCopied(null),1500)};
  const exportJson=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),products:products.length,orders:orders.length,records:rows},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`yalla-supabase-diagnostics-${Date.now()}.json`;a.click();URL.revokeObjectURL(url);showToast('Diagnostics export downloaded','success')};
  return <div className="space-y-6">
    <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white p-5 rounded-3xl border border-slate-200/80 shadow-xs"><div className="flex items-center gap-3"><div className="w-12 h-12 rounded-2xl bg-indigo-50 border border-indigo-100 flex items-center justify-center text-indigo-600"><Activity className="w-6 h-6"/></div><div><div className="flex items-center gap-2"><h2 className="text-base font-bold">Supabase Database Monitor & Security Audit</h2><span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-emerald-100 text-emerald-800 border border-emerald-200">● Active Monitoring</span></div><p className="text-xs text-slate-500">Tracks database-enforced administrative operations, targets, snapshots, actors and realtime changes.</p></div></div><div className="flex flex-wrap gap-2"><button onClick={runDiagnostic} disabled={running} className="px-3.5 py-2 bg-indigo-600 disabled:opacity-50 text-white text-xs font-semibold rounded-xl flex items-center gap-2">{running?<RefreshCw className="w-3.5 h-3.5 animate-spin"/>:<Zap className="w-3.5 h-3.5"/>}{running?'Testing…':'Run Supabase Health Ping'}</button><button onClick={exportJson} className="px-3 py-2 bg-slate-100 text-slate-700 text-xs font-semibold rounded-xl flex items-center gap-1.5"><Download className="w-3.5 h-3.5"/>Export JSON</button><button onClick={load} className="px-3 py-2 bg-slate-100 text-slate-700 text-xs font-semibold rounded-xl"><RefreshCw className="w-3.5 h-3.5"/></button></div></div>
    <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 gap-3"><div className="bg-white p-4 rounded-2xl border shadow-xs"><span className="text-[11px] text-slate-500">Total Operations</span><div className="text-xl font-bold mt-1">{rows.length}</div></div><div className="bg-white p-4 rounded-2xl border shadow-xs"><span className="text-[11px] text-slate-500">Writes</span><div className="text-xl font-bold mt-1">{rows.filter(r=>/insert|update|delete|write/i.test(r.operation||r.action_type||'')).length}</div></div><div className="bg-white p-4 rounded-2xl border shadow-xs"><span className="text-[11px] text-slate-500">Catalog Items</span><div className="text-xl font-bold mt-1">{products.length}</div></div><div className="bg-white p-4 rounded-2xl border shadow-xs"><span className="text-[11px] text-slate-500">Orders</span><div className="text-xl font-bold mt-1">{orders.length}</div></div><div className="bg-white p-4 rounded-2xl border shadow-xs"><span className="text-[11px] text-slate-500">Failed/Error</span><div className="text-xl font-bold mt-1 text-rose-600">{rows.filter(r=>/fail|error/i.test(`${r.operation} ${r.action_type} ${r.summary}`)).length}</div></div><div className="bg-white p-4 rounded-2xl border shadow-xs"><span className="text-[11px] text-slate-500">Realtime</span><div className="text-xl font-bold mt-1 text-emerald-600">ON</div></div></div>
    {diagnostic&&<div className={`p-4 rounded-2xl border flex items-start gap-3 ${diagnostic.ok?'bg-emerald-50 border-emerald-200':'bg-rose-50 border-rose-200'}`}>{diagnostic.ok?<CheckCircle2 className="w-5 h-5 text-emerald-600"/>:<AlertCircle className="w-5 h-5 text-rose-600"/>}<div className="text-xs"><b>{diagnostic.ok?'Supabase Read Health Check Passed':'Supabase Health Check Failed'}</b><p className="mt-1">{diagnostic.message}</p></div></div>}
    <div className="flex items-center justify-between border-b pb-2"><div className="flex gap-2"><button onClick={()=>setTab('operations')} className={`px-4 py-2 text-xs font-bold rounded-xl flex gap-2 items-center ${tab==='operations'?'bg-[#4f46e5] text-white':'bg-white border'}`}><Terminal className="w-3.5 h-3.5"/>Supabase Operations Monitor ({filtered.length})</button><button onClick={()=>setTab('pipeline')} className={`px-4 py-2 text-xs font-bold rounded-xl flex gap-2 items-center ${tab==='pipeline'?'bg-[#4f46e5] text-white':'bg-white border'}`}><Layers className="w-3.5 h-3.5"/>Data Pipeline Audit</button></div><span className="text-[11px] text-slate-400 hidden sm:block">RLS-protected audit history</span></div>
    <div className="bg-white p-4 rounded-2xl border shadow-xs"><div className="relative"><Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search actor, action, table, target, IP, details..." className="w-full pl-10 pr-4 py-2 bg-slate-50 rounded-xl border text-xs"/></div></div>
    <div className="bg-white rounded-3xl border shadow-xs overflow-hidden"><div className="p-4 bg-slate-50/70 border-b flex items-center justify-between"><div className="flex items-center gap-2"><Clock className="w-4 h-4 text-slate-400"/><span className="text-xs font-bold uppercase tracking-wider">{tab==='operations'?'Supabase Low-Level Audit Stream':'Pipeline Audit Stream'} ({filtered.length} events)</span></div></div><div className="divide-y max-h-[680px] overflow-y-auto">{loading?<div className="p-16 text-center text-slate-400">Loading audit events…</div>:filtered.length===0?<div className="p-16 text-center text-slate-400"><Database className="w-8 h-8 mx-auto mb-2"/>No audit operations logged yet.</div>:filtered.map(r=>{const open=expanded===r.id;return <div key={r.id} onClick={()=>setExpanded(open?null:r.id)} className="p-4 hover:bg-slate-50 cursor-pointer"><div className="flex items-start justify-between gap-4"><div className="space-y-1.5 flex-1"><div className="flex flex-wrap gap-2 items-center"><span className="px-2 py-0.5 rounded-lg text-[10px] font-bold bg-indigo-50 text-indigo-700 border">{r.operation||r.action_type||'AUDIT'}</span><span className="font-mono text-xs font-bold text-indigo-700 bg-indigo-50/60 px-2 py-0.5 rounded-md">{r.table_name||'—'}</span><span className="text-[11px] text-slate-500">target: <b>{r.target_id||'—'}</b></span></div><p className="text-xs text-slate-800">{r.summary||r.details||'Administrative database activity'}</p></div><div className="flex items-center gap-2"><span className="text-[11px] font-mono text-slate-400">{new Date(r.created_at).toLocaleString()}</span><button onClick={e=>{e.stopPropagation();copyLog(r)}} className="p-1 text-slate-400 hover:text-indigo-600">{copied===r.id?<Check className="w-3.5 h-3.5 text-emerald-600"/>:<Copy className="w-3.5 h-3.5"/>}</button>{open?<ChevronUp className="w-4 h-4 text-slate-400"/>:<ChevronDown className="w-4 h-4 text-slate-400"/>}</div></div>{open&&<div className="mt-3 pt-3 border-t space-y-2 text-xs" onClick={e=>e.stopPropagation()}><div className="grid grid-cols-2 sm:grid-cols-4 gap-2 bg-slate-50 p-3 rounded-xl"><div><b>Actor:</b> {r.actor_id||'system'}</div><div><b>Operation:</b> {r.operation||r.action_type||'—'}</div><div><b>IP:</b> {r.ip_address||'—'}</div><div><b>User Agent:</b> {r.user_agent||'—'}</div></div>{r.snapshot_before!==undefined&&<pre className="bg-slate-900 text-amber-300 p-3 rounded-xl overflow-auto text-[11px]">{JSON.stringify(r.snapshot_before,null,2)}</pre>}{r.snapshot_after!==undefined&&<pre className="bg-slate-900 text-emerald-300 p-3 rounded-xl overflow-auto text-[11px]">{JSON.stringify(r.snapshot_after,null,2)}</pre>}</div>}</div>})}</div></div>
    <div className="bg-slate-900 text-white p-5 rounded-3xl shadow-sm space-y-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Cpu className="w-4 h-4 text-indigo-400"/><span className="text-xs font-bold uppercase tracking-wider text-slate-300">Supabase Data Flow & Security Pipeline</span></div><div className="text-[11px] text-slate-400 flex items-center gap-1.5"><ShieldCheck className="w-3.5 h-3.5 text-emerald-400"/>RLS + database-enforced audit trail</div></div><div className="grid grid-cols-1 sm:grid-cols-5 gap-3 pt-2 text-xs"><div className="bg-white/5 border border-white/10 p-3 rounded-2xl"><b className="text-blue-300">1. Form Input</b><p className="text-[11px] text-slate-300 mt-1">Admin changes a managed record.</p></div><div className="bg-white/5 border border-white/10 p-3 rounded-2xl"><b className="text-purple-300">2. Validation</b><p className="text-[11px] text-slate-300 mt-1">Client and database constraints validate data.</p></div><div className="bg-white/5 border border-white/10 p-3 rounded-2xl"><b className="text-amber-300">3. Supabase Write</b><p className="text-[11px] text-slate-300 mt-1">Postgres mutation executes under RLS.</p></div><div className="bg-white/5 border border-white/10 p-3 rounded-2xl"><b className="text-emerald-300">4. DB Audit</b><p className="text-[11px] text-slate-300 mt-1">Administrative activity is recorded with actor and target.</p></div><div className="bg-white/5 border border-white/10 p-3 rounded-2xl"><b className="text-cyan-300">5. Realtime Sync</b><p className="text-[11px] text-slate-300 mt-1">Realtime subscribers refresh the admin console.</p></div></div></div>
  </div>;
};
export default DatabaseActivityLogs;
