import React, { useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase';

export const DatabaseActivityLogs: React.FC = () => {
  const [rows,setRows]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [query,setQuery]=useState('');
  const load=async()=>{setLoading(true);const {data,error}=await supabase.from('admin_activities').select('*').order('created_at',{ascending:false}).limit(250);if(error)setError(error.message);else setRows(data||[]);setLoading(false)};
  useEffect(()=>{load()},[]);
  const filtered=rows.filter(r=>{const q=query.trim().toLowerCase();return !q||[r.action_type,r.summary,r.table_name,r.operation,r.target_id,r.actor_id,r.ip_address].filter(Boolean).some(v=>String(v).toLowerCase().includes(q))});
  return <section className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">Security & Audit Logs</h2><p className="text-sm text-slate-500">Immutable database-enforced administrative history with actor, operation, target, IP and user agent.</p></div><button onClick={load} className="px-3 py-2 rounded-xl bg-slate-100 font-bold text-sm">Refresh</button></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter user, action, table, entity, IP..." className="w-full px-4 py-3 rounded-2xl border border-slate-200 bg-white"/>{loading?<div className="p-8 bg-white rounded-2xl border text-center">Loading audit log…</div>:error?<div className="p-8 bg-rose-50 text-rose-700 rounded-2xl border border-rose-200">{error}</div>:<div className="bg-white border rounded-2xl overflow-auto"><table className="w-full text-sm"><thead><tr className="bg-slate-50 text-left"><th className="p-3">Time</th><th className="p-3">Actor</th><th className="p-3">Action</th><th className="p-3">Table</th><th className="p-3">Target</th><th className="p-3">IP</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t align-top"><td className="p-3 whitespace-nowrap">{new Date(r.created_at).toLocaleString()}</td><td className="p-3 font-mono text-xs">{r.actor_id||'system'}</td><td className="p-3 font-bold">{r.operation||r.action_type}</td><td className="p-3">{r.table_name||'—'}</td><td className="p-3 font-mono text-xs">{r.target_id||'—'}</td><td className="p-3 text-xs">{r.ip_address||'—'}</td></tr>)}{filtered.length===0&&<tr><td colSpan={6} className="p-8 text-center text-slate-500">No audit events found.</td></tr>}</tbody></table></div>}</section>;
};

export default DatabaseActivityLogs;
