import React from 'react';
import { Eye, Image as ImageIcon, ShoppingBag, Star, Truck, ShieldCheck } from 'lucide-react';
import { useShop } from '../../context/ShopContext';
import type { SectionVisibilityConfig } from '../../types';

type Device = 'desktop' | 'tablet' | 'mobile';
interface Props { order: string[]; visibility: SectionVisibilityConfig; device: Device; }
const labels: Record<string,string>={homeHero:'Hero / Main Banner',homeCategories:'Categories',homeFeatured:'Featured Products',homeDeals:'Deals',homeBundles:'Bundles',homeNews:'News',homeNewArrivals:'New Arrivals',homeTrustBadges:'Trust & Benefits',homeHeritage:'Heritage / Story',homeReviews:'Customer Reviews',homeNewsletter:'Newsletter'};
const widthClass: Record<Device,string>={desktop:'max-w-[1180px]',tablet:'max-w-[768px]',mobile:'max-w-[390px]'};
export const ReadOnlyStorefrontPreview: React.FC<Props>=({order,visibility,device})=>{
 const {siteContent,categories=[],products=[],productBundles=[],language}=useShop(); const content=siteContent as any,home=content?.home||{},hero=content?.hero||{},news=content?.newsSection||{},isAr=language==='ar';
 const media=(hero.bgMediaItems||[]).filter((x:any)=>x?.isPublished!==false),heroImage=media[0]?.url||media[0]?.desktopImageUrl||hero.bgImageUrl||hero.desktopImageUrl,heroMobileImage=media[0]?.mobileUrl||media[0]?.mobileImageUrl||hero.mobileImageUrl||heroImage;
 const heroTitle=isAr?(media[0]?.customTitleArabic||hero.titleArabic||media[0]?.customTitle||hero.title):(media[0]?.customTitle||hero.title),heroSubtitle=isAr?(media[0]?.customSubtitleArabic||hero.subtitleArabic||media[0]?.customSubtitle||hero.subtitle):(media[0]?.customSubtitle||hero.subtitle),heroButton=isAr?(media[0]?.buttonTextArabic||hero.primaryBtnTextArabic||media[0]?.buttonText||hero.primaryBtnText):(media[0]?.buttonText||hero.primaryBtnText);
 const publishedCategories=categories.filter((x:any)=>x?.isPublished!==false).sort((a:any,b:any)=>(a?.displayOrder??999)-(b?.displayOrder??999)).slice(0,6),liveProducts=products.filter((x:any)=>x?.isPublished!==false).sort((a:any,b:any)=>(a?.displayOrder??999)-(b?.displayOrder??999)),liveBundles=productBundles.filter((x:any)=>x?.isActive!==false&&x?.showInSlider!==false).slice(0,6),publishedNews=(news.articles||[]).filter((x:any)=>x?.isPublished!==false).slice(0,3);
 const empty=(title:string)=><div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 px-5 py-8 text-center"><ShoppingBag className="w-7 h-7 mx-auto text-slate-300"/><p className="mt-2 text-sm font-bold text-slate-600">{title}</p><p className="mt-1 text-xs text-slate-400">No live data is available, so this preview does not fabricate content.</p></div>;
 const cards=(items:any[])=>(!items.length?empty('No matching published products'):<div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">{items.slice(0,8).map((p:any)=>{const name=isAr?(p.arabicName||p.name):p.name,image=p.image||p.additionalImages?.[0],price=Number(p.priceUSD),original=Number(p.originalPriceUSD),discount=Number(p.discountPercentage)>0||original>price;return <article key={p.id} className="rounded-xl overflow-hidden border border-slate-200 bg-white"><div className="aspect-square bg-slate-100 flex items-center justify-center">{image?<img src={image} alt={name||'Product'} loading="lazy" className="w-full h-full object-contain"/>:<ImageIcon className="w-8 h-8 text-slate-300"/>}</div><div className="p-3"><div className="text-[11px] font-bold line-clamp-2 min-h-[2rem]">{name||'Unnamed product'}</div><div className="mt-2 flex items-center gap-2"><span className="text-sm font-black">{Number.isFinite(price)?`$${price.toFixed(2)}`:'—'}</span>{discount&&Number.isFinite(original)?<span className="text-[10px] text-slate-400 line-through">${original.toFixed(2)}</span>:null}</div>{p.stock<=0?<div className="mt-1 text-[9px] font-bold text-rose-500">Out of stock</div>:null}</div></article>})}</div>);
 const section=(id:string)=>{if(visibility[id as keyof SectionVisibilityConfig]===false)return null;
  if(id==='homeHero')return <section key={id} className="relative overflow-hidden bg-slate-950 min-h-[300px] sm:min-h-[390px] flex items-center">{heroImage?<><picture className="absolute inset-0"><source media="(max-width:640px)" srcSet={heroMobileImage||heroImage}/><img src={heroImage} alt="CMS hero" className="w-full h-full object-cover opacity-75"/></picture><div className="absolute inset-0 bg-black/35"/></>:<div className="absolute inset-0 bg-gradient-to-br from-slate-900 to-slate-700"/>}<div className="relative z-10 p-7 sm:p-12 max-w-2xl text-white">{hero.badgeText||hero.badgeTextArabic?<div className="text-[10px] uppercase tracking-[0.2em] font-bold text-amber-200 mb-3">{isAr?(hero.badgeTextArabic||hero.badgeText):(hero.badgeText||hero.badgeTextArabic)}</div>:null}<h2 className="text-3xl sm:text-5xl font-black tracking-tight">{heroTitle||(isAr?'واجهة المتجر الرئيسية':'Your Storefront Hero')}</h2>{heroSubtitle?<p className="mt-3 text-sm sm:text-base text-white/80 max-w-xl">{heroSubtitle}</p>:null}{heroButton?<span className="inline-flex mt-6 px-5 py-2.5 rounded-xl bg-white text-slate-950 text-xs font-black">{heroButton}</span>:null}</div><div className="absolute top-3 right-3 rounded-full bg-black/50 text-white px-2.5 py-1 text-[9px] font-bold flex items-center gap-1"><Eye className="w-3 h-3"/> READ-ONLY PREVIEW</div></section>;
  if(id==='homeCategories')return <section key={id} className="px-4 sm:px-6 py-7"><div className="mb-5"><div className="text-[10px] uppercase tracking-[0.2em] font-bold text-[#8F7137]">{isAr?(home.categoriesSubtitleArabic||'تصفح الأقسام'):(home.categoriesSubtitle||'Browse Departments')}</div><h2 className="text-2xl font-serif font-bold mt-1">{isAr?(home.categoriesTitleArabic||'تسوق حسب الفئات'):(home.categoriesTitle||'Explore by Category')}</h2></div>{publishedCategories.length?<div className="grid grid-cols-2 sm:grid-cols-3 gap-3">{publishedCategories.map((c:any)=><div key={c.id} className="rounded-xl overflow-hidden border border-slate-200 bg-white"><div className="aspect-square bg-slate-100 flex items-center justify-center">{c.bannerUrl?<img src={c.bannerUrl} alt={isAr?c.nameAr:c.nameEn} className="w-full h-full object-contain"/>:<ImageIcon className="w-8 h-8 text-slate-300"/>}</div><div className="p-3 text-xs font-bold">{isAr?(c.nameAr||c.nameEn):(c.nameEn||c.nameAr)}</div></div>)}</div>:empty(isAr?'لا توجد فئات منشورة':'No published categories')}</section>;
  if(id==='homeFeatured')return <section key={id} className="px-4 sm:px-6 py-7"><h2 className="text-xl font-black mb-4">{labels[id]}</h2>{cards(liveProducts.filter((p:any)=>p.isFeatured||p.isBestseller||(p.displayOrder!==undefined&&p.displayOrder<=50)))}</section>;
  if(id==='homeDeals')return <section key={id} className="px-4 sm:px-6 py-7"><h2 className="text-xl font-black mb-4">{labels[id]}</h2>{cards(liveProducts.filter((p:any)=>Number(p.discountPercentage)>0||Number(p.originalPriceUSD)>Number(p.priceUSD)))}</section>;
  if(id==='homeNewArrivals')return <section key={id} className="px-4 sm:px-6 py-7"><h2 className="text-xl font-black mb-4">{labels[id]}</h2>{cards(liveProducts.filter((p:any)=>p.isNewArrival===true).sort((a:any,b:any)=>new Date(b.createdAt||0).getTime()-new Date(a.createdAt||0).getTime()))}</section>;
  if(id==='homeBundles')return <section key={id} className="px-4 sm:px-6 py-7"><h2 className="text-xl font-black mb-4">{isAr?(home.bundlesTitleArabic||home.bundlesTitle||labels[id]):(home.bundlesTitle||labels[id])}</h2>{liveBundles.length?<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">{liveBundles.map((b:any)=><article key={b.id} className="rounded-xl overflow-hidden border border-slate-200 bg-white">{b.imageUrl?<img src={b.imageUrl} alt={isAr?(b.nameAr||b.name):b.name} className="w-full aspect-[16/9] object-cover"/>:null}<div className="p-4"><h3 className="text-sm font-black">{isAr?(b.nameAr||b.name):b.name}</h3>{b.description||b.descriptionAr?<p className="text-xs text-slate-500 mt-1 line-clamp-3">{isAr?(b.descriptionAr||b.description):b.description}</p>:null}<div className="mt-3 text-sm font-black">${Number(b.bundlePriceUSD).toFixed(2)}</div></div></article>)}</div>:empty('No published bundles')}</section>;
  if(id==='homeNews')return <section key={id} className="px-4 sm:px-6 py-7"><h2 className="text-xl font-black">{isAr?(news.titleArabic||news.title||labels[id]):(news.title||labels[id])}</h2>{publishedNews.length?<div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mt-4">{publishedNews.map((a:any)=><article key={a.id} className="rounded-xl overflow-hidden border border-slate-200 bg-white">{a.imageUrl?<img src={a.imageUrl} alt={isAr?(a.titleArabic||a.title):a.title} className="w-full aspect-[16/9] object-cover"/>:null}<div className="p-4"><div className="text-[9px] uppercase tracking-wider font-bold text-[#8F7137]">{isAr?(a.tagArabic||a.tag):a.tag}</div><h3 className="text-sm font-black mt-1 line-clamp-2">{isAr?(a.titleArabic||a.title):a.title}</h3><p className="text-xs text-slate-500 mt-2 line-clamp-3">{isAr?(a.excerptArabic||a.excerpt):a.excerpt}</p></div></article>)}</div>:empty('No published news articles')}</section>;
  if(id==='homeHeritage')return <section key={id} className="px-4 sm:px-6 py-8"><div className="rounded-2xl bg-white border border-slate-200 p-6 sm:p-8"><h2 className="text-2xl font-serif font-bold">{isAr?(home.heritageTitleArabic||home.heritageTitle||labels[id]):(home.heritageTitle||labels[id])}</h2><p className="text-sm text-slate-600 leading-7 mt-3 whitespace-pre-line">{isAr?(home.heritageTextArabic||home.heritageText||''):(home.heritageText||home.heritageTextArabic||'')}</p></div></section>;
  if(id==='homeReviews')return <section key={id} className="px-4 sm:px-6 py-7"><h2 className="text-xl font-black mb-2 flex items-center gap-2"><Star className="w-5 h-5"/>{isAr?(home.reviewsTitleArabic||home.reviewsTitle||labels[id]):(home.reviewsTitle||labels[id])}</h2>{empty('No published customer reviews')}</section>;
  if(id==='homeNewsletter')return <section key={id} className="px-4 sm:px-6 py-8"><div className="rounded-2xl bg-slate-100 p-7 text-center"><h2 className="text-xl font-black">{isAr?(home.newsletterTitleArabic||home.newsletterTitle||'Stay in the loop'):(home.newsletterTitle||'Stay in the loop')}</h2><p className="text-xs text-slate-500 mt-2">{isAr?(home.newsletterSubtitleArabic||home.newsletterSubtitle||''):(home.newsletterSubtitle||home.newsletterSubtitleArabic||'')}</p><span className="mt-4 inline-flex h-10 px-5 items-center rounded-xl bg-white border border-slate-200 text-xs font-bold">{isAr?(home.newsletterButtonTextArabic||home.newsletterButtonText||'Subscribe'):(home.newsletterButtonText||'Subscribe')}</span></div></section>;
  if(id==='homeTrustBadges'){const badges=[{icon:ShieldCheck,title:home.trustBadge1Title,titleAr:home.trustBadge1TitleArabic,text:home.trustBadge1Text,textAr:home.trustBadge1TextArabic},{icon:Truck,title:home.trustBadge2Title,titleAr:home.trustBadge2TitleArabic,text:home.trustBadge2Text,textAr:home.trustBadge2TextArabic}].filter((b:any)=>b.title||b.titleAr||b.text||b.textAr);return <section key={id} className="px-4 sm:px-6 py-7"><h2 className="text-xl font-black mb-4">{labels[id]}</h2>{badges.length?<div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{badges.map((b:any,i:number)=>{const Icon=b.icon;return <div key={i} className="rounded-xl border border-slate-200 bg-white p-4 flex gap-3"><Icon className="w-5 h-5 shrink-0"/><div><h3 className="text-sm font-bold">{isAr?(b.titleAr||b.title):(b.title||b.titleAr)}</h3><p className="text-xs text-slate-500 mt-1">{isAr?(b.textAr||b.text):(b.text||b.textAr)}</p></div></div>})}</div>:empty('No CMS trust-benefit content configured')}</section>}
  return <section key={id} className="px-4 sm:px-6 py-7">{empty(labels[id]||id)}</section>;
 };
 return <div className="mx-auto w-full bg-white text-slate-900 overflow-hidden rounded-2xl shadow-sm border border-slate-200"><div className={`mx-auto w-full ${widthClass[device]}`}>{order.map(section)}</div></div>;
};