import React, { useEffect, useMemo, useState } from 'react';
import { Search, TrendingUp, Clock, Download, Trash2, Sparkles, ExternalLink, Copy, Check, BarChart2, Zap, User, Globe, AlertCircle, RefreshCw, Flame } from 'lucide-react';
import { useShop } from '../../context/ShopContext';
import { supabase } from '../../lib/supabase';
import { csvSafe } from '../../utils/csvSafe';

type SearchRow = { id:string; user_id?:string|null; query:string; origin?:string|null; created_at:string; };
type TimeRange = 'all'|'24h'|'7d'|'30d';

export const SearchAnalyticsView: React.FC = () => {
  const { setActiveTab, setSearchQuery:setGlobalSearchQuery, logSearchQuery, showToast } = useShop();
  const [logs,setLogs]=useState<SearchRow[]>([]); const [loading,setLoading]=useState(true); const [range,setRange]=useState<TimeRange>('all'); const [filter,setFilter]=useState(''); const [copied,setCopied]=useState<string|null>(null); const [input,setInput]=useState(''); const [clearing,setClearing]=useState(false); const [confirmClear,setConfirmClear]=useState(false);
  const load=async()=>{const {data,error}=await supabase.from('search_logs').select('id,user_id,query,origin,created_at').order('created_at',{ascending:false}).limit(1000);if(error)showToast('Failed to load search analytics','warning');else setLogs((data||[]) as SearchRow[]);setLoading(false)};
  useEffect(()=>{load(); const ch=supabase.channel('search-analytics-live').on('postgres_changes',{event:'*',schema:'public',table:'search_logs'},()=>load()).subscribe(); return()=>{void supabase.removeChannel(ch)}},[]);
  const filtered=useMemo(()=>{const now=Date.now();const cut=range==='24h'?now-86400000:range==='7d'?now-604800000:range==='30d'?now-2592000000:0;return logs.filter(l=>(!cut||new Date(l.created_at).getTime()>=cut)&&(!filter||l.query.toLowerCase().includes(filter.toLowerCase())))},[logs,range,filter]);
  const trends=useMemo(()=>{const m=new Map<string,{count:number,last:string,first:string,origins:Set<string>}>();filtered.forEach(l=>{const q=l.query.trim();if(!q)return;const e=m.get(q)||{count:0,last:l.created_at,first:l.created_at,origins:new Set<string>()};e.count++;if(new Date(l.created_at)>new Date(e.last))e.last=l.created_at;if(new Date(l.created_at)<new Date(e.first))e.first=l.created_at;if(l.origin)e.origins.add(l.origin);m.set(q,e)});return [...m.entries()].map(([term,d])=>({term,...d})).sort((a,b)=>b.count-a.count)},[filtered]);
  const top=trends[0]; const last24=logs.filter(l=>Date.now()-new Date(l.created_at).getTime()<86400000).length;
  const copy=(term:string)=>{navigator.clipboard.writeText(term);setCopied(term);showToast(`Copied "${term}" to clipboard`,'info');setTimeout(()=>setCopied(null),1500)};
  const inspect=(term:string)=>{setGlobalSearchQuery(term);setActiveTab('products');window.scrollTo({top:0,behavior:'smooth'});showToast(`Filtering catalog by "${term}"`,'info')};
  const exportCsv=()=>{if(!trends.length)return showToast('No search trends data to export yet','warning');const rows=trends.map((t,i)=>({rank:i+1,search_term:csvSafe(t.term),search_count:t.count,percentage_of_total:`${((t.count/Math.max(1,filtered.length))*100).toFixed(1)}%`,first_searched:new Date(t.first).toLocaleString(),last_searched:new Date(t.last).toLocaleString()}));const csv=['rank,search_term,search_count,percentage_of_total,first_searched,last_searched',...rows.map(r=>`${r.rank},"${String(r.search_term).replace(/"/g,'""')}",${r.search_count},${r.percentage_of_total},"${r.first_searched}","${r.last_searched}"`)].join('\n');const blob=new Blob([csv],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`yalla_search_trends_${range}_${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);showToast('Search trends CSV report downloaded successfully','success')};
  const simulate=async(term:string)=>{if(!term.trim())return;try{await logSearchQuery(term.trim(),'direct');setInput('');showToast(`Logged search query: "${term.trim()}"`,'success')}catch{showToast('Failed to log test search','error')}};
  const clear=async()=>{setClearing(true);const {error}=await supabase.from('search_logs').delete().not('id','is',null);if(error)showToast(error.message,'error');else{setLogs([]);setConfirmClear(false);showToast('Search trends history cleared','success')}setClearing(false)};
  const rel=(d:string)=>{const mins=Math.floor((Date.now()-new Date(d).getTime())/60000);if(mins<1)return'Just now';if(mins<60)return`${mins}m ago`;const h=Math.floor(mins/60);if(h<24)return`${h}h ago`;const days=Math.floor(h/24);return days<7?`${days}d ago`:new Date(d).toLocaleDateString([], {month:'short',day:'numeric'})};

  return <div className="space-y-6">
    <div className="bg-white p-6 sm:p-7 rounded-3xl border border-slate-200 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-4"><div className="flex items-center gap-2.5"><div className="w-10 h-10 rounded-2xl bg-amber-50 text-[#b89753] flex items-center justify-center border border-amber-200/60"><TrendingUp className="w-5 h-5"/></div><div><div className="flex items-center gap-2"><h2 className="text-xl sm:text-2xl font-black">Search Trends & Discovery Analytics</h2><span className="hidden sm:inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[10px] font-extrabold bg-emerald-50 text-emerald-700 border border-emerald-200">● Live Stream</span></div><p className="text-xs text-slate-500">Live monitoring of search queries, shopper interests, and catalog demand across Lebanon.</p></div></div><div className="flex gap-2"><button onClick={exportCsv} className="px-4 py-2.5 bg-slate-50 text-slate-700 font-bold text-xs rounded-xl border"><Download className="w-3.5 h-3.5 inline mr-1"/>Export CSV</button>{logs.length>0&&<button onClick={()=>setConfirmClear(true)} className="px-3 py-2.5 bg-rose-50 text-rose-700 font-bold text-xs rounded-xl border border-rose-200"><Trash2 className="w-3.5 h-3.5 inline mr-1"/>Clear History</button>}</div></div>
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4"><div className="bg-white p-5 rounded-3xl border shadow-xs"><span className="text-[11px] font-bold text-slate-500 uppercase">Total Searches</span><div className="text-3xl font-black mt-2">{filtered.length}</div><span className="text-xs text-slate-400">logged</span></div><div className="bg-white p-5 rounded-3xl border shadow-xs"><span className="text-[11px] font-bold text-slate-500 uppercase">Unique Keywords</span><div className="text-3xl font-black mt-2">{trends.length}</div><span className="text-xs text-slate-400">distinct queries</span></div><div className="bg-white p-5 rounded-3xl border shadow-xs"><span className="text-[11px] font-bold text-slate-500 uppercase">Top Search</span><div className="text-xl font-black mt-3 truncate">{top?.term||'—'}</div><span className="text-xs text-emerald-700">{top?.count||0} queries</span></div><div className="bg-white p-5 rounded-3xl border shadow-xs"><span className="text-[11px] font-bold text-slate-500 uppercase">Today's Activity</span><div className="text-3xl font-black mt-2">{last24}</div><span className="text-xs text-slate-400">in last 24h</span></div></div>
    <div className="flex flex-col sm:flex-row justify-between gap-3 bg-slate-100/70 p-2 rounded-2xl border"><div className="flex gap-1 bg-white p-1 rounded-xl border">{([{id:'all',label:'All Time'},{id:'24h',label:'Last 24 Hours'},{id:'7d',label:'Past 7 Days'},{id:'30d',label:'Past 30 Days'}] as const).map(x=><button key={x.id} onClick={()=>setRange(x.id)} className={`px-3 py-1.5 rounded-lg text-xs font-bold whitespace-nowrap ${range===x.id?'bg-slate-900 text-white':'text-slate-600 hover:bg-slate-50'}`}>{x.label}</button>)}</div><div className="relative sm:max-w-xs flex-1"><Search className="w-3.5 h-3.5 absolute left-3 top-2.5 text-slate-400"/><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Filter keywords in table..." className="w-full pl-9 pr-3 py-1.5 bg-white text-xs rounded-xl border"/></div></div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><div className="lg:col-span-2 bg-white rounded-3xl border shadow-xs overflow-hidden"><div className="p-5 border-b flex justify-between"><div className="flex gap-2"><BarChart2 className="w-4 h-4 text-[#b89753]"/><h3 className="font-extrabold text-sm">Most Popular Search Terms</h3></div><span className="text-[11px] text-slate-400">Showing {trends.length} keywords</span></div>{loading?<div className="p-16 text-center">Loading…</div>:<div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500 font-bold"><tr><th className="p-3">Rank</th><th className="p-3">Search Keyword</th><th className="p-3 text-center">Frequency</th><th className="p-3">Share</th><th className="p-3 text-right">Last Searched</th><th className="p-3 text-right">Actions</th></tr></thead><tbody className="divide-y">{trends.slice(0,50).map((t,i)=>{const pct=filtered.length?((t.count/filtered.length)*100):0;return <tr key={t.term} className="hover:bg-slate-50"><td className="p-3 font-bold">{i+1}</td><td className="p-3 font-bold">{t.term}</td><td className="p-3 text-center"><span className="px-2.5 py-1 rounded-full bg-amber-50 text-[#b89753] border">{t.count}</span></td><td className="p-3"><div className="text-[10px] mb-1">{pct.toFixed(1)}%</div><div className="w-full bg-slate-100 rounded-full h-1.5"><div className="bg-amber-500 h-1.5 rounded-full" style={{width:`${Math.min(100,Math.max(8,pct))}%`}}/></div></td><td className="p-3 text-right text-slate-500">{rel(t.last)}</td><td className="p-3"><div className="flex justify-end gap-1"><button onClick={()=>copy(t.term)} className="p-1.5 bg-slate-100 rounded-lg">{copied===t.term?<Check className="w-3.5 h-3.5 text-emerald-600"/>:<Copy className="w-3.5 h-3.5"/>}</button><button onClick={()=>inspect(t.term)} className="p-1.5 bg-amber-50 text-amber-800 rounded-lg"><ExternalLink className="w-3.5 h-3.5"/></button></div></td></tr>})}</tbody></table>{!trends.length&&<div className="p-16 text-center text-slate-400"><Search className="w-8 h-8 mx-auto mb-2"/>No search logs recorded yet.</div>}</div>}</div>
      <div className="space-y-6"><div className="bg-white rounded-3xl border shadow-xs overflow-hidden"><div className="p-5 border-b flex justify-between"><div className="flex gap-2"><Clock className="w-4 h-4 text-violet-600"/><h3 className="font-extrabold text-sm">Live Recent Searches</h3></div><span className="text-[10px] bg-violet-50 px-2 py-0.5 rounded-full">Latest 20</span></div><div className="p-3 space-y-2 max-h-[460px] overflow-y-auto">{filtered.slice(0,20).map(l=><div key={l.id} className="p-2.5 rounded-2xl hover:bg-slate-50 flex justify-between gap-3"><div><div className="flex gap-2 items-center"><Search className="w-3.5 h-3.5 text-slate-400"/><b className="text-xs">{l.query}</b></div><div className="text-[10px] text-slate-400 mt-1">{l.origin||'search'} • {l.user_id?<><User className="w-2.5 h-2.5 inline"/> customer</>:<><Globe className="w-2.5 h-2.5 inline"/> guest</>}</div></div><span className="text-[10px] text-slate-400">{rel(l.created_at)}</span></div>)}</div></div><div className="bg-gradient-to-br from-slate-900 to-slate-800 text-white rounded-3xl p-5 shadow-md space-y-4"><div className="flex items-center gap-2"><Zap className="w-4 h-4 text-amber-400"/><h4 className="text-xs font-extrabold uppercase text-amber-300">Admin Search Pipeline Test</h4></div><p className="text-xs text-slate-300">Verify real-time tracking by injecting a test query.</p><div className="flex flex-wrap gap-1.5">{['Zaatar Baladi','Olive Oil Koura','Soap of Tripoli','Debs El Remman','Kishk','Cedar Wood'].map(s=><button key={s} onClick={()=>simulate(s)} className="text-[10px] font-bold px-2.5 py-1 bg-white/10 rounded-lg">+ {s}</button>)}</div><div className="flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&simulate(input)} placeholder="Type custom test query..." className="flex-1 px-3 py-2 bg-white/10 text-xs rounded-xl border border-white/15"/><button onClick={()=>simulate(input)} disabled={!input.trim()} className="px-3 py-2 bg-amber-500 text-slate-950 text-xs font-extrabold rounded-xl">Log</button></div></div></div></div>
    {confirmClear&&<div className="fixed inset-0 z-50 bg-slate-900/60 flex items-center justify-center p-4"><div className="bg-white rounded-3xl p-6 max-w-md w-full space-y-4"><AlertCircle className="w-8 h-8 text-rose-600 mx-auto"/><h3 className="text-base font-extrabold text-center">Clear All Search Analytics Logs?</h3><p className="text-xs text-slate-500 text-center">This permanently deletes all recorded search queries.</p><div className="flex gap-3"><button onClick={()=>setConfirmClear(false)} className="flex-1 py-2.5 bg-slate-100 rounded-xl text-xs font-bold">Cancel</button><button onClick={clear} disabled={clearing} className="flex-1 py-2.5 bg-rose-600 text-white rounded-xl text-xs font-bold">{clearing?'Clearing...':'Confirm Clear'}</button></div></div></div>}
  </div>;
};
export default SearchAnalyticsView;
