import React,{useEffect,useMemo,useState} from 'react';
import Papa from 'papaparse';
import {Store,Search,Eye,EyeOff,Trash2,Plus,Edit3,Download,Upload,CheckCircle2,XCircle,UserPlus,Phone,Mail,MessageCircle,RefreshCw,MapPin,ShieldCheck} from 'lucide-react';
import {useShop} from '../../context/ShopContext';
import {supabase} from '../../lib/supabase';
import {secureRandomString} from '../../utils/uuid';

const GOV:any={Beirut:['Beirut'],'Mount Lebanon':['Baabda','Aley','Chouf','Keserwan','Matn','Jbeil'],North:['Tripoli','Zgharta','Bsharri','Batroun','Koura','Minieh-Dinnieh'],Akkar:['Akkar'],Bekaa:['Zahle','West Bekaa','Rashaya'],'Baalbek-Hermel':['Baalbek','Hermel'],South:['Saida','Jezzine','Tyre'],Nabatieh:['Nabatieh','Bint Jbeil','Hasbaya','Marjeyoun']};
const norm=(v:string)=>{let s=(v||'').replace(/[^0-9+]/g,'');if(s.startsWith('00'))s='+'+s.slice(2);if(/^0[35789]/.test(s))s='+961'+s;return s};
const valid=(v:string)=>/^\+961(3|70|71|76|78|79|81)\d{6}$/.test(norm(v));
const safe=(v:any)=>{const s=String(v??'');return /^[=+\-@]/.test(s)?"'"+s:s};
const dl=(data:any[],name:string)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([Papa.unparse(data)],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
const blank=()=>({nameEn:'',nameAr:'',sellerCode:'',contactPhone:'',contactEmail:'',governorate:'',district:'',village:'',exactAddress:'',craftCategory:'',region:'',commissionPct:'',logoUrl:'',bannerImage:'',bioEn:'',bioAr:'',isActive:true});

export const SellersView:React.FC=()=>{
 const s=useShop() as any; const sellers=s.sellers||[], products=s.products||[], categories=s.categories||[]; const [tab,setTab]=useState('registered'); const [q,setQ]=useState(''); const [form,setForm]=useState<any>(null); const [apps,setApps]=useState<any[]>([]); const [csv,setCsv]=useState(''); const [preview,setPreview]=useState<any[]>([]); const [errors,setErrors]=useState<string[]>([]); const [target,setTarget]=useState(''); const [fallback,setFallback]=useState(''); const [busy,setBusy]=useState(false);
 const rows=useMemo(()=>sellers.filter((x:any)=>!q||[x.nameEn,x.nameAr,x.id,x.sellerCode,x.governorate,x.district,x.village,x.contactPhone,x.contactEmail].filter(Boolean).some((v:any)=>String(v).toLowerCase().includes(q.toLowerCase()))),[sellers,q]);
 const count=(id:string)=>products.filter((p:any)=>p.sellerId===id).length;
 const loadApps=async()=>{setBusy(true);try{const r=await supabase.from('seller_applications').select('*').order('created_at',{ascending:false});if(r.error)throw r.error;setApps(r.data||[])}catch(e:any){s.showToast(e.message||'Could not load applications.','error')}finally{setBusy(false)}};
 useEffect(()=>{if(tab==='signups')loadApps()},[tab]);
 const save=async(e:any)=>{e.preventDefault();if(!form.nameEn.trim())return s.showToast('English seller name is required.','warning');if(form.contactPhone&&!valid(form.contactPhone))return s.showToast('Enter a valid Lebanese phone/WhatsApp number.','warning');try{const p={nameEn:form.nameEn.trim(),nameAr:form.nameAr||undefined,sellerCode:form.sellerCode||undefined,contactPhone:form.contactPhone?norm(form.contactPhone):undefined,contactEmail:form.contactEmail||undefined,governorate:form.governorate||undefined,district:form.district||undefined,village:form.village||undefined,exactAddress:form.exactAddress||undefined,craftCategory:form.craftCategory||undefined,region:form.region||undefined,commissionPct:form.commissionPct===''?undefined:Number(form.commissionPct),logoUrl:form.logoUrl||undefined,bannerImage:form.bannerImage||undefined,bioEn:form.bioEn||undefined,bioAr:form.bioAr||undefined,isActive:!!form.isActive};if(form.id)await s.updateSeller(form.id,p);else await s.addSeller(p);s.showToast(form.id?'Seller updated.':'Seller created.','success');setForm(null)}catch(e:any){s.showToast(e.message||'Could not save seller.','error')}};
 const remove=async(x:any)=>{if(count(x.id))return s.showToast('Reassign linked products before deleting this seller.','warning');if(!confirm('Delete seller '+x.nameEn+'?'))return;try{await s.deleteSeller(x.id);s.showToast('Seller deleted.','success')}catch(e:any){s.showToast(e.message||'Delete failed.','error')}};
 const provision=async(x:any)=>{const email=x.accountEmail||x.contactEmail;if(!email)return s.showToast('Business email is required.','warning');const pw=secureRandomString(14);try{const r=await supabase.functions.invoke('admin-seller-provision',{body:{sellerId:x.id,email,password:pw}});if(r.error)throw r.error;alert('Seller portal credentials\n\nEmail: '+email+'\nTemporary password: '+pw+'\n\nSave them securely.');s.showToast('Seller portal account provisioned.','success')}catch(e:any){s.showToast(e.message||'Provisioning failed.','error')}};
 const approve=async(a:any)=>{const p=a.payload||{};try{await s.addSeller({nameEn:String(p.name_en||p.nameEn||p.business_name||p.name||'Applicant'),nameAr:p.name_ar||p.nameAr,contactPhone:p.phone||p.contact_phone||p.whatsapp,contactEmail:p.email||p.contact_email,governorate:p.governorate,district:p.district,village:p.village||p.city||p.town,exactAddress:p.exact_address||p.address,craftCategory:p.category||p.craft_category,bioEn:p.workshop_description||p.description,bioAr:p.description_ar,isActive:true});const r=await supabase.from('seller_applications').update({status:'approved',updated_at:new Date().toISOString()}).eq('id',a.id);if(r.error)throw r.error;s.showToast('Application approved and seller created.','success');loadApps()}catch(e:any){s.showToast(e.message||'Approval failed.','error')}};
 const decline=async(a:any)=>{const reason=prompt('Feedback reason:','Additional photos required');if(reason===null)return;const r=await supabase.from('seller_applications').update({status:'declined',payload:{...(a.payload||{}),decline_reason:reason},updated_at:new Date().toISOString()}).eq('id',a.id);if(r.error)s.showToast(r.error.message,'error');else{ s.showToast('Application declined with feedback.','success');loadApps()}};
 const dryRun=(text:string)=>{setCsv(text);const r=Papa.parse(text,{header:true,skipEmptyLines:true,transformHeader:h=>h.trim().toLowerCase()});const seen=new Set<string>(),er:string[]=[];const pv=(r.data as any[]).map((x:any,i)=>{const sku=String(x.sku||x.id||x.product_id||'').trim(),name=String(x.name_en||x.name||x.title||'').trim();let status='Ready';if(!name)status='Missing name';if(x.price_usd!==undefined&&(!Number.isFinite(Number(x.price_usd))||Number(x.price_usd)<=0))status='Invalid price';if(sku&&seen.has(sku.toLowerCase()))status='Duplicate SKU';if(sku)seen.add(sku.toLowerCase());if(status!=='Ready')er.push('Row '+(i+2)+': '+status);return{row:i+2,sku,name,seller:x.seller_id||x.seller||'',category:x.category_id||x.category||'',action:products.some((p:any)=>p.id===sku)?'Update':'Create',status}});setPreview(pv);setErrors(er)};
 const commit=async()=>{try{const r=await s.bulkImportProducts(csv,{targetSellerId:target||undefined,fallbackCategoryId:fallback||undefined});s.showToast('Import: '+r.created+' created, '+r.updated+' updated, '+r.errors.length+' errors.','success');setErrors(r.errors);if(!r.errors.length)setPreview([])}catch(e:any){s.showToast(e.message||'Import failed.','error')}};
 const exportSellers=()=>dl(rows.map((x:any)=>({seller_id:safe(x.id),seller_code:safe(x.sellerCode),name_en:safe(x.nameEn),name_ar:safe(x.nameAr),phone:safe(x.contactPhone),email:safe(x.contactEmail),governorate:safe(x.governorate),district:safe(x.district),village:safe(x.village),address:safe(x.exactAddress),active:x.isActive?'yes':'no',products:count(x.id)})),'yalla-sellers.csv');
 const exportMaster=()=>dl(products.map((p:any)=>({id:safe(p.id),name_en:safe(p.name),name_ar:safe(p.arabicName),description_en:safe(p.description),description_ar:safe(p.craftStory),price_usd:p.priceUSD,stock:p.stock,seller_id:safe(p.sellerId),category_id:safe(p.category),badge:safe((p.tags||[]).join('|')),image_url:safe(p.image),seller_item_code:safe(p.sellerItemCode),is_published:p.isPublished?'yes':'no'})),'yalla-master-catalog.csv');
 return <section className="space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">Sellers & Bulk Import</h2><p className="text-sm text-slate-500">Complete vendor operations for Lebanon.</p></div><div className="flex gap-2"><button onClick={()=>dl([{id:'',name_en:'',name_ar:'',description_en:'',description_ar:'',price_usd:'',stock:'',seller_id:'',category_id:'',badge:'',image_url:'',seller_item_code:'',is_published:'yes'}],'yalla-catalog-template.csv')} className="px-3 py-2 rounded-xl bg-slate-100 text-xs font-black"><Download className="inline w-4 h-4 mr-1"/>Template</button><button onClick={exportSellers} className="px-3 py-2 rounded-xl bg-slate-100 text-xs font-black">Sellers CSV</button><button onClick={exportMaster} className="px-3 py-2 rounded-xl bg-slate-100 text-xs font-black">Master Export</button></div></div>
  <div className="bg-white border rounded-2xl p-1 flex gap-1"><button onClick={()=>setTab('registered')} className={'flex-1 px-3 py-3 rounded-xl text-sm font-black '+(tab==='registered'?'bg-slate-900 text-white':'text-slate-500')}>Registered Sellers ({sellers.length})</button><button onClick={()=>setTab('signups')} className={'flex-1 px-3 py-3 rounded-xl text-sm font-black '+(tab==='signups'?'bg-slate-900 text-white':'text-slate-500')}>Seller Signups ({apps.filter((a:any)=>a.status==='pending').length})</button><button onClick={()=>setTab('bulk')} className={'flex-1 px-3 py-3 rounded-xl text-sm font-black '+(tab==='bulk'?'bg-slate-900 text-white':'text-slate-500')}>CSV Bulk Import / Export</button></div>
  {tab==='registered'&&<><div className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search seller, ID, phone, governorate, district..." className="w-full pl-10 pr-4 py-3 rounded-2xl border"/></div><button onClick={()=>setForm(blank())} className="px-4 py-3 rounded-2xl bg-slate-900 text-white font-black"><Plus className="inline w-4 h-4"/> Add Seller</button></div>
  {form&&<form onSubmit={save} className="bg-white border rounded-3xl p-5 space-y-3"><div className="flex justify-between"><h3 className="font-black">{form.id?'Edit Seller':'Add Seller'}</h3><button type="button" onClick={()=>setForm(null)}><XCircle/></button></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-3">{[['nameEn','English Name *'],['nameAr','Arabic Name'],['sellerCode','Seller ID / Code'],['contactPhone','Lebanese WhatsApp / Phone'],['contactEmail','Business Email'],['village','Village / Town'],['exactAddress','Exact Physical Address'],['craftCategory','Craft Category'],['region','Regional Code'],['commissionPct','Commission %'],['logoUrl','Logo URL'],['bannerImage','Banner Image URL']].map((z:any)=><input key={z[0]} value={form[z[0]]||''} onChange={e=>setForm((v:any)=>({...v,[z[0]]:e.target.value}))} placeholder={z[1]} className="px-3 py-2.5 rounded-xl border"/>)}</div><div className="grid md:grid-cols-2 gap-3"><select value={form.governorate} onChange={e=>setForm((v:any)=>({...v,governorate:e.target.value,district:''}))} className="px-3 py-2.5 rounded-xl border"><option value="">Governorate</option>{Object.keys(GOV).map(g=><option key={g}>{g}</option>)}</select><select value={form.district} onChange={e=>setForm((v:any)=>({...v,district:e.target.value}))} className="px-3 py-2.5 rounded-xl border"><option value="">District / Qada</option>{(GOV[form.governorate]||[]).map((d:string)=><option key={d}>{d}</option>)}</select></div><textarea value={form.bioEn||''} onChange={e=>setForm((v:any)=>({...v,bioEn:e.target.value}))} placeholder="Workshop description — English" className="w-full px-3 py-2.5 rounded-xl border"/><textarea value={form.bioAr||''} onChange={e=>setForm((v:any)=>({...v,bioAr:e.target.value}))} placeholder="Workshop description — Arabic" className="w-full px-3 py-2.5 rounded-xl border"/><label className="flex gap-2 text-sm font-bold"><input type="checkbox" checked={!!form.isActive} onChange={e=>setForm((v:any)=>({...v,isActive:e.target.checked}))}/> Active storefront visibility</label><button className="px-5 py-3 rounded-xl bg-slate-900 text-white font-black"><ShieldCheck className="inline w-4 h-4 mr-1"/>Save Seller</button></form>}
  <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{rows.map((x:any)=><article key={x.id} className={'bg-white border rounded-2xl p-5 '+(x.isActive===false?'opacity-70':'')}><div className="flex gap-3"><div className="w-10 h-10 rounded-xl bg-slate-100 flex items-center justify-center"><Store className="w-5 h-5"/></div><div className="flex-1"><h3 className="font-black">{x.nameEn}</h3><p className="text-xs text-slate-500">{x.nameAr||'—'} · {x.sellerCode||x.id}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div><MapPin className="inline w-3 h-3"/> {x.governorate||'—'}<br/><b>{x.district||x.village||'—'}</b></div><div>Products<br/><b>{count(x.id)}</b></div><div>Phone<br/><b>{x.contactPhone||'—'}</b></div><div>Status<br/><b>{x.isActive===false?'Inactive':'Active'}</b></div></div><div className="mt-4 flex justify-end gap-1"><a href={x.contactPhone?'https://wa.me/'+norm(x.contactPhone).replace('+',''):undefined} target="_blank" rel="noreferrer" className="p-2 rounded-lg"><MessageCircle className="w-4 h-4"/></a><a href={x.contactPhone?'tel:'+norm(x.contactPhone):undefined} className="p-2 rounded-lg"><Phone className="w-4 h-4"/></a><a href={x.contactEmail?'mailto:'+x.contactEmail:undefined} className="p-2 rounded-lg"><Mail className="w-4 h-4"/></a><button onClick={()=>setForm({...blank(),...x})} className="p-2"><Edit3 className="w-4 h-4"/></button><button onClick={()=>s.toggleSellerActive(x.id,x.isActive===false)} className="p-2">{x.isActive===false?<Eye/>:<EyeOff/>}</button><button onClick={()=>provision(x)} className="p-2"><UserPlus className="w-4 h-4"/></button><button onClick={()=>remove(x)} className="p-2 text-rose-600"><Trash2 className="w-4 h-4"/></button></div></article>)}</div></>}
  {tab==='signups'&&<div className="space-y-3"><button onClick={loadApps} className="px-3 py-2 rounded-xl bg-slate-100 text-xs font-black"><RefreshCw className={busy?'inline w-4 h-4 mr-1 animate-spin':'inline w-4 h-4 mr-1'}/>Refresh</button>{apps.map((a:any)=><article key={a.id} className="bg-white border rounded-2xl p-5"><div className="flex justify-between"><div><h3 className="font-black">{a.payload?.name_en||a.payload?.name||'Seller Applicant'}</h3><p className="text-xs text-slate-500">{a.payload?.email||a.payload?.contact_email||'No email'} · {a.payload?.phone||a.payload?.whatsapp||'No phone'}</p><p className="text-xs text-slate-500 mt-1">{a.payload?.governorate||'—'} / {a.payload?.district||'—'} / {a.payload?.village||a.payload?.city||'—'}</p></div><span className="px-2 py-1 rounded-full bg-slate-100 text-xs font-black">{a.status}</span></div><p className="text-sm text-slate-600 mt-3">{a.payload?.workshop_description||a.payload?.description||'No workshop description.'}</p>{a.status==='pending'&&<div className="mt-4 flex gap-2"><button onClick={()=>approve(a)} className="px-3 py-2 rounded-xl bg-emerald-50 text-emerald-700 text-xs font-black"><CheckCircle2 className="inline w-4 h-4"/> Approve</button><button onClick={()=>decline(a)} className="px-3 py-2 rounded-xl bg-rose-50 text-rose-700 text-xs font-black"><XCircle className="inline w-4 h-4"/> Decline / Feedback</button></div>}</article>)}</div>}
  {tab==='bulk'&&<div className="space-y-4"><div className="bg-white border rounded-2xl p-5"><h3 className="font-black">CSV Smart Dry Run</h3><p className="text-xs text-slate-500 mt-1">PapaParse validates the file in memory before the existing Supabase bulk-import service commits rows.</p><div className="flex flex-wrap gap-2 mt-3"><select value={target} onChange={e=>setTarget(e.target.value)} className="px-3 py-2 rounded-xl border text-sm"><option value="">Auto-detect seller</option>{sellers.map((x:any)=><option key={x.id} value={x.id}>{x.nameEn}</option>)}</select><select value={fallback} onChange={e=>setFallback(e.target.value)} className="px-3 py-2 rounded-xl border text-sm"><option value="">No fallback category</option>{categories.map((x:any)=><option key={x.id} value={x.id}>{x.nameEn}</option>)}</select><label className="px-3 py-2 rounded-xl bg-slate-100 text-xs font-black cursor-pointer"><Upload className="inline w-4 h-4"/> Upload CSV<input type="file" accept=".csv,text/csv" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)f.text().then(dryRun)}}/></label></div><textarea value={csv} onChange={e=>setCsv(e.target.value)} placeholder="id,name_en,name_ar,price_usd,stock,seller_id,category_id..." className="w-full min-h-40 border rounded-xl p-3 font-mono text-xs"/><div className="flex gap-2"><button onClick={()=>dryRun(csv)} className="px-4 py-2 rounded-xl bg-indigo-50 text-indigo-700 font-black text-sm">Dry Run Preview</button><button onClick={commit} disabled={!preview.length||errors.length>0} className="px-4 py-2 rounded-xl bg-slate-900 text-white font-black text-sm">Commit Clean Rows</button></div></div>{preview.length>0&&<div className="bg-white border rounded-2xl overflow-auto"><table className="w-full text-xs"><thead className="bg-slate-50"><tr>{['Row','SKU','Product','Seller','Category','Action','Status'].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{preview.map((r:any)=><tr key={r.row} className="border-t"><td className="p-3">{r.row}</td><td className="p-3">{r.sku||'—'}</td><td className="p-3">{r.name||'—'}</td><td className="p-3">{r.seller||'—'}</td><td className="p-3">{r.category||'—'}</td><td className="p-3">{r.action}</td><td className="p-3">{r.status}</td></tr>)}</tbody></table></div>}{errors.length>0&&<div className="bg-rose-50 border border-rose-200 rounded-2xl p-4 text-sm text-rose-700"><b>Validation errors</b><ul className="list-disc ml-5">{errors.map((e,i)=><li key={i}>{e}</li>)}</ul></div>}</div>}
 </section>
};
export default SellersView;