declare module 'firebase/firestore' {
  export type DocumentData = Record<string, any>;
  export type SetOptions = { merge?: boolean };
  export type FirestoreDataConverter<T> = { toFirestore(value: T): DocumentData; fromFirestore(snapshot: QueryDocumentSnapshot, options?: SnapshotOptions): T };
  export type SnapshotOptions = { serverTimestamps?: 'estimate' | 'previous' | 'none' };
  export type QueryDocumentSnapshot<T = DocumentData> = { id: string; data(options?: SnapshotOptions): T; exists(): true };
  export type QuerySnapshot<T = DocumentData> = { docs: QueryDocumentSnapshot<T>[]; empty: boolean; size: number; forEach(callback: (doc: QueryDocumentSnapshot<T>) => void): void };
  export type DocumentSnapshot<T = DocumentData> = { id: string; data(options?: SnapshotOptions): T | undefined; exists(): boolean };
  export type CollectionReference<T = DocumentData> = any;
  export type DocumentReference<T = DocumentData> = any;
  export type Query<T = DocumentData> = any;
  export type QueryConstraint = any;
  export type WriteBatch = any;
  export type Firestore = any;
  export const collection: any;
  export const doc: any;
  export const query: any;
  export const where: any;
  export const orderBy: any;
  export const limit: any;
  export function getDocs<T = DocumentData>(q: any): Promise<QuerySnapshot<T>>;
  export function getDoc<T = DocumentData>(q: any): Promise<DocumentSnapshot<T>>;
  export function getDocFromServer<T = DocumentData>(q: any): Promise<DocumentSnapshot<T>>;
  export const addDoc: any;
  export const setDoc: any;
  export const updateDoc: any;
  export const deleteDoc: any;
  export const onSnapshot: any;
  export const writeBatch: any;
  export const serverTimestamp: any;
  export const Timestamp: any;
  export const documentId: any;
  export const FieldPath: any;
}
