import React,{useEffect,useRef,useState} from 'react';
import { ShieldCheck,ArrowRight,RefreshCw,X,AlertCircle } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useDialog } from '../hooks/useDialog';
import { safeErrorMessage } from '../utils/errorSanitizer';

interface OTPModalProps{isOpen:boolean;onClose:()=>void;onVerifySuccess:()=>Promise<void>|void;targetContact:string;actionType:'login'|'signup'|'admin'|'seller';language?:'en'|'ar'}
export const OTPModal:React.FC<OTPModalProps>=({isOpen,onClose,onVerifySuccess,targetContact,actionType,language='en'})=>{
 const [otp,setOtp]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [timer,setTimer]=useState(60);const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(!isOpen)return;setOtp('');setError('');setNotice('');setTimer(60);void sendOtp();},[isOpen,targetContact]);
 useEffect(()=>{if(timer<=0)return;const t=window.setInterval(()=>setTimer(v=>Math.max(0,v-1)),1000);return()=>window.clearInterval(t)},[timer]);
 const sendOtp=async()=>{if(!targetContact)return;setBusy(true);setError('');try{if(targetContact.includes('@')){const {error}=await supabase.auth.signInWithOtp({email:targetContact.trim().toLowerCase(),options:{shouldCreateUser:actionType==='signup'}});if(error)throw error;setNotice('A verification code was sent to your email.');setTimer(60);}else{throw new Error('Phone OTP is disabled in this Supabase migration. Use email OTP.');}}catch(e:unknown){setError(safeErrorMessage(e,'Could not send the verification code.'))}finally{setBusy(false)}};
 const verify=async()=>{const code=otp.replace(/\D/g,'');if(code.length<6){setError('Enter the verification code.');return;}setBusy(true);setError('');try{const {data,error}=await supabase.auth.verifyOtp({email:targetContact.trim().toLowerCase(),token:code,type:'email'});if(error)throw error;if(!data.user)throw new Error('Verification did not create a session.');await onVerifySuccess();onClose();}catch(e:unknown){setError(safeErrorMessage(e,'Invalid or expired code.'))}finally{setBusy(false)}};
 const {containerRef}=useDialog({isOpen,onClose});
 if(!isOpen)return null;const ar=language==='ar';
 return <div role="dialog" aria-modal="true" aria-label={ar?'التحقق من البريد':'Verify your email'} className="fixed inset-0 z-[80] bg-black/50 flex items-center justify-center p-4"><div ref={containerRef} className="w-full max-w-md bg-white rounded-3xl p-6 shadow-2xl"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><ShieldCheck className="w-5 h-5 text-[#B89753]"/><h2 className="font-black">{ar?'التحقق من البريد':'Verify your email'}</h2></div><button onClick={onClose} aria-label="Close"><X className="w-5 h-5"/></button></div><p className="text-sm text-slate-500 mt-2">{notice||`Enter the code sent to ${targetContact}.`}</p><input ref={input} autoFocus inputMode="numeric" maxLength={8} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))} className="w-full mt-5 px-4 py-4 rounded-2xl border text-center text-2xl tracking-[0.4em] font-mono" placeholder="000000"/><div className="min-h-6 mt-2 text-xs text-rose-600 flex gap-1">{error&&<><AlertCircle className="w-4 h-4"/>{error}</>}</div><button disabled={busy||otp.length<6} onClick={verify} className="w-full mt-3 py-3 rounded-xl bg-slate-900 text-white font-bold disabled:opacity-50 flex items-center justify-center gap-2">{busy?'Verifying…':<>Verify<ArrowRight className="w-4 h-4"/></>}</button><button disabled={busy||timer>0} onClick={sendOtp} className="w-full mt-3 py-2 text-sm font-bold text-slate-600 disabled:opacity-40 flex items-center justify-center gap-2">{timer>0?`Resend in ${timer}s`:<><RefreshCw className="w-4 h-4"/>Resend code</>}</button></div></div>;
};
