drop policy if exists analytics_admin_read on public.analytics_events;
create policy analytics_admin_read on public.analytics_events for select to authenticated using ((select has_permission('analytics.view')));
drop policy if exists analytics_insert_public on public.analytics_events;
create policy analytics_insert_public on public.analytics_events for insert to anon,authenticated with check ((user_id is null) or (user_id=(select auth.uid())));
drop policy if exists analytics_own_read on public.analytics_events;
create policy analytics_own_read on public.analytics_events for select to authenticated using (user_id=(select auth.uid()));
drop policy if exists inventory_admin_all on public.inventory_ledger;
create policy inventory_admin_all on public.inventory_ledger for all to authenticated using ((select has_permission('inventory.manage'))) with check ((select has_permission('inventory.manage')));
drop policy if exists inventory_seller_read_own on public.inventory_ledger;
create policy inventory_seller_read_own on public.inventory_ledger for select to authenticated using ((select has_permission('inventory.manage_own')) and seller_id=(select profiles.seller_id from public.profiles where profiles.id=(select auth.uid())));
drop policy if exists notifications_admin on public.notifications;
create policy notifications_admin on public.notifications for all to authenticated using ((select has_permission('notifications.manage'))) with check ((select has_permission('notifications.manage')));
drop policy if exists notifications_own on public.notifications;
create policy notifications_own on public.notifications for select to authenticated using ((user_id=(select auth.uid())) or (select has_permission('notifications.manage')));
drop policy if exists notifications_update_own on public.notifications;
create policy notifications_update_own on public.notifications for update to authenticated using (user_id=(select auth.uid())) with check (user_id=(select auth.uid()));
drop policy if exists order_events_admin on public.order_events;
create policy order_events_admin on public.order_events for all to authenticated using ((select has_permission('orders.manage'))) with check ((select has_permission('orders.manage')));
drop policy if exists order_events_customer_read_own on public.order_events;
create policy order_events_customer_read_own on public.order_events for select to authenticated using (exists(select 1 from public.orders o where o.id=order_events.order_id and o.user_id=(select auth.uid())));
drop policy if exists user_permissions_admin on public.user_permissions;
create policy user_permissions_admin on public.user_permissions for all to authenticated using ((select is_admin())) with check ((select is_admin()));
drop policy if exists user_permissions_self on public.user_permissions;
create policy user_permissions_self on public.user_permissions for select to authenticated using ((user_id=(select auth.uid())) or (select is_admin()));
